---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: all
  connection: local
  gather_facts: False
  vars:
    - tenant: "test_tenant"

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant created using ansible"
