---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    tenant : "tenant"
    filters:
      - "https"
      - "sql"
    filter_entries:
      - filter: "https"
        entry: "https"
        port:  443
      - filter: "sql"
        entry:  "sql"
        port:  1433
    contracts:
      - "web"
      - "sql"
    contract_subjects:
      - contract: "web"
        subject: "https"
      - contract: "sql"
        subject: "sql"
    contract_subject_to_filters:
      - contract: "web"
        subject:  "https"
        filter:   "https"
      - contract: "sql"
        subject:  "sql"
        filter:   "sql"

  tasks:
    - name: ENSURE TENANT FILTERS EXIST
      aci_filter:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        filter: "{{ item.filter }}"
        descr: "Filter Created Using Ansible"
      with_items: "{{ filters }}"

    - name: ENSURE FILTERS HAVE FILTER ENTRIES
      aci_filter_entry:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        filter: "{{ item.filter }}"
        entry: "{{ item.entry }}"
        ether_type: "ip"
        ip_protocol: "tcp"
        dst_port_start: "{{ item.port }}"
        dst_port_end: "{{ item.port }}"
      with_items: "{{ filter_entries }}"

    - name: ENSURE TENANT CONTRACTS EXIST
      aci_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        contract: "{{ item }}"
        scope: "context"
        description: "Contract Created Using Ansible"
      with_items: "{{ contracts }}"

    - name: ENSURE CONTRACTS HAVE CONTRACT SUBJECTS
      aci_contract_subject:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
      with_items: "{{ contract_subjects }}"

    - name: ENSURE CONTRACTS SUBJECTS ARE ASSOCIATED WITH FILTERS
      aci_contract_subject_to_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant_name: "{{ tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
        filter: "{{ item.filter }}"
      with_items: "{{ contract_subject_filters }}"
