---
- name: USE ACI REST MODULE
  hosts: all
  connection: local
  gather_facts: False

  vars:
    path: "api/mo/uni/tn-test_tenant.json"

  tasks:
    - name: ENSURE LAB WORK IS CLEANED UP
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        method: "delete"
        validate_certs: False
        path: "{{ path }}"
